### PR TITLE
consolidated html scripts to single file to make upkeep easier

### PR DESCRIPTION
**Pull request by devinpearson**
Looking to make the HTML site usable across all OS's as well as easier to maintain.

If happy to go in this direction. I will change the rest of the scripts to work in the same way.

### CODE REVIEW

**Comment by shermand100** [comment]
Hi this is fantastic. I was going to make an example pull of just moving all the php to one directory and the txt files to another but this is far more elegant. I wouldn't have thought to approach this like this with my experience level.

That cleans all the php files nicely. Is there a way of dealing with the .txt files other than consolidating them into a separate directory. They're the results of commands such as `free -h` for system memory for example so the interface can display it.

**Comment by shermand100** [comment]
@devinpearson Just checking in.
Loved the progress then I didn't comment further because this pull had the "draft" tag, although it looked close.
Does this require testing or help/input from me?
I'm keen to get these changes in just wondering if I've misinterpreted the draft tag.

**Comment by devinpearson** [comment]
It just needs to be tested. I have a partially built v5 node at the moment

**Comment by devinpearson** [comment]
@shermand100 I've cleared up the merge conflicts. Can you test the functions

**Comment by shermand100** [comment]
So testing last night was great no issues at all. Simple to implement, understand and greatly reduces the previous clutter. A massive +1 for the basic error handling for "Error: No function specified". Thanks so much for your work on this. I assume it was tedious just going through changing all those links.

I'll merge this and then improve the updater script separately. I need to improve the updater because current behaviour will overwrite /var/www/html/ files but not remove the old .php clutter.  `rm -R /www/www/html/*.php` before the move should fix this.

**Pull request merged**
